* improved logging, updates regarding config files
git-svn-id: @592 -

diff --git a/scripts/updatetestsuite b/scripts/updatetestsuite
--- a/scripts/updatetestsuite
+++ b/scripts/updatetestsuite
@@ -4,17 +4,19 @@
 #set -e
 
 TESTSUITEDIR=/FPC/testsuite
-LOGFILE=$HOME/logs/updatetestsuite.log
 INCOMINGDIR=$TESTSUITEDIR/incoming
 FAILEDDIR=$TESTSUITEDIR/failed
 WORKDIR=$TESTSUITEDIR/work
-TESTSOURCEDIR=$TESTSUITEDIR/tests
+TESTSOURCEDIR=$TESTSUITEDIR/testsuite
 TESTSUITEBINDIR=$TESTSUITEDIR/bin
+DATENAME=`date +%Y-%m-%d-%k-%M-%S`
+LOGFILE=$HOME/logs/updatetestsuite.$DATENAME.log
+DBCFG=$TESTSUITEBINDIR/dbdigest.cfg.dbdata
 
 # processfile <file>
 processfile() {
   echo
-  echo "Found file $1"
+  echo "`date`: Start processing file $1"
   echo
 
   basefn=`basename $1`
@@ -29,20 +31,29 @@ processfile() {
     # remove unit paths from testsuite parameters
     sed -e 's/-Fu[^ ]*//' < dbdigest.cfg > dbdigest.cfg.new
     mv dbdigest.cfg.new dbdigest.cfg
-    echo "DatabaseName=TESTSUITE" >> dbdigest.cfg
-    echo "UserName=FPCUser" >> dbdigest.cfg
-    echo "PassWord=Shimrod" >> dbdigest.cfg
+
+#    better avoid usernames and passwords in the script (available in SVN among others)
+#     echo "DatabaseName=TESTSUITE" >> dbdigest.cfg
+#     echo "UserName=yyy" >> dbdigest.cfg
+#     echo "PassWord=xxx" >> dbdigest.cfg
+    if [ -f $DBCFG ]; then
+     cat $DBCFG >> dbdigest.cfg
+
 #    doesn't work if hostname contains number
 #    date=`echo $1 | sed 's/[^0-9]*\([0-9]*\)[^0-9]*/\1/'`
 #   next won't work if hostname contains 12 consecutive numbers, better (jonas)
-    date=`echo $1 | sed 's/.*\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\).*/\1/'`
-    echo "Date=$date" >> dbdigest.cfg
-    echo "TestSrcDir=$TESTSOURCEDIR" >> dbdigest.cfg
+     date=`echo $1 | sed 's/.*\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\).*/\1/'`
+     echo "Date=$date" >> dbdigest.cfg
+     echo "TestSrcDir=$TESTSOURCEDIR" >> dbdigest.cfg
 
-    $TESTSUITEBINDIR/dbdigest
-    err=$?
+     $TESTSUITEBINDIR/dbdigest
+     err=$?
+    else
+     echo "ERROR: No dbdigest.cfg found!"
+     err=1
+    fi
   else
-    echo "ERROR: No dbdigest.cfg found!"
+    echo "ERROR: No $DBCFG found!"
     err=1
   fi
 
@@ -76,4 +87,7 @@ svn up
 for f in $FILES; do
     processfile $f
 done
+echo "`date`: Finished.
 ) > $LOGFILE 2>&1 </dev/null
+
+gzip $LOGFILE
